In [5]:
import pandas as pd
df = pd.read_csv('/content/train.csv')
df.head()

id  ... label
0   0  ...     1
1   1  ...     0
2   2  ...     1
3   3  ...     1
4   4  ...     1

[5 rows x 5 columns]

In [6]:
X = df.drop('label', axis = 1)
y = df['label'] 
X.head()

id  ...                                               text
0   0  ...  House Dem Aide: We Didn’t Even See Comey’s Let...
1   1  ...  Ever get the feeling your life circles the rou...
2   2  ...  Why the Truth Might Get You Fired October 29, ...
3   3  ...  Videos 15 Civilians Killed In Single US Airstr...
4   4  ...  Print \r\nAn Iranian woman has been sentenced ...

[5 rows x 4 columns]

In [7]:

df = df.dropna()
df.head(10)

id  ... label
0    0  ...     1
1    1  ...     0
2    2  ...     1
3    3  ...     1
4    4  ...     1
5    5  ...     0
7    7  ...     0
9    9  ...     0
10  10  ...     0
11  11  ...     0

[10 rows x 5 columns]

In [8]:
messages = df.copy()
messages.reset_index(inplace = True)
messages.head(10)

index  id  ...                                               text label
0      0   0  ...  House Dem Aide: We Didn’t Even See Comey’s Let...     1
1      1   1  ...  Ever get the feeling your life circles the rou...     0
2      2   2  ...  Why the Truth Might Get You Fired October 29, ...     1
3      3   3  ...  Videos 15 Civilians Killed In Single US Airstr...     1
4      4   4  ...  Print \r\nAn Iranian woman has been sentenced ...     1
5      5   5  ...  In these trying times, Jackie Mason is the Voi...     0
6      7   7  ...  PARIS  —   France chose an idealistic, traditi...     0
7      9   9  ...  A week before Michael T. Flynn resigned as nat...     0
8     10  10  ...  Organizing for Action, the activist group that...     0
9     11  11  ...  The BBC produced spoof on the “Real Housewives...     0

[10 rows x 6 columns]

In [10]:
messages['all'] = messages['title'] + ' ' + messages['author'] + ' ' + messages['text']
messages['all'][1]

'FLYNN: Hillary Clinton, Big Woman on Campus - Breitbart Daniel J. Flynn Ever get the feeling your life circles the roundabout rather than heads in a straight line toward the intended destination? [Hillary Clinton remains the big woman on campus in leafy, liberal Wellesley, Massachusetts. Everywhere else votes her most likely to don her inauguration dress for the remainder of her days the way Miss Havisham forever wore that wedding dress.  Speaking of Great Expectations, Hillary Rodham overflowed with them 48 years ago when she first addressed a Wellesley graduating class. The president of the college informed those gathered in 1969 that the students needed “no debate so far as I could ascertain as to who their spokesman was to be” (kind of the like the Democratic primaries in 2016 minus the   terms unknown then even at a Seven Sisters school). “I am very glad that Miss Adams made it clear that what I am speaking for today is all of us —  the 400 of us,” Miss Rodham told her classmates

In [27]:
import nltk
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('punkt')


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Error loading stem: Package 'stem' not found in index


False

In [33]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
import re
ps = PorterStemmer()
corpus = []
for i in range(0, len(messages)):
    review = re.sub('[^a-zA-Z]', ' ', messages['all'][i])
    review = review.lower()
    review = review.split()
    
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [36]:
corpus[1]

'flynn hillari clinton big woman campu breitbart daniel j flynn ever get feel life circl roundabout rather head straight line toward intend destin hillari clinton remain big woman campu leafi liber wellesley massachusett everywher els vote like inaugur dress remaind day way miss havisham forev wore wed dress speak great expect hillari rodham overflow year ago first address wellesley graduat class presid colleg inform gather student need debat far could ascertain spokesman kind like democrat primari minu term unknown even seven sister school glad miss adam made clear speak today us us miss rodham told classmat appoint edger bergen charli mccarthi mortim snerd attend bespectacl granni glass award matronli wisdom least john lennon wisdom took issu previou speaker despit becom first win elect seat u senat sinc reconstruct edward brook came critic call empathi goal protestor critic tactic though clinton senior thesi saul alinski lament black power demagogu elitist arrog repress intoler with

In [37]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer, HashingVectorizer
cv = CountVectorizer(max_features=5000,ngram_range=(1,3))
X=cv.fit_transform(corpus).toarray()


In [39]:
X.shape
y = messages['label']

In [41]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=0)
cv.get_feature_names()[:20]

['aaron',
 'abandon',
 'abc',
 'abe',
 'abedin',
 'abil',
 'abl',
 'abort',
 'abroad',
 'absenc',
 'absolut',
 'absorb',
 'absurd',
 'abu',
 'abus',
 'academ',
 'academi',
 'acceler',
 'accept',
 'access']

In [42]:
cv.get_params()

{'analyzer': 'word',
 'binary': False,
 'decode_error': 'strict',
 'dtype': numpy.int64,
 'encoding': 'utf-8',
 'input': 'content',
 'lowercase': True,
 'max_df': 1.0,
 'max_features': 5000,
 'min_df': 1,
 'ngram_range': (1, 3),
 'preprocessor': None,
 'stop_words': None,
 'strip_accents': None,
 'token_pattern': '(?u)\\b\\w\\w+\\b',
 'tokenizer': None,
 'vocabulary': None}

In [45]:
count_df = pd.DataFrame(X_train, columns=cv.get_feature_names())
count_df.head()

aaron  abandon  abc  abe  abedin  ...  zero  zika  zionist  zone  zu
0      0        0    0    0       0  ...     0     0        0     0   0
1      0        0    0    0       0  ...     0     0        0     0   0
2      0        0    0    0       0  ...     0     0        0     0   0
3      0        0    0    0       0  ...     0     0        0     0   0
4      0        0    0    0       0  ...     0     0        0     0   0

[5 rows x 5000 columns]

In [47]:
from sklearn.naive_bayes import MultinomialNB
classifier=MultinomialNB()

from sklearn import metrics
import numpy as np
import itertools

In [48]:
classifier.fit(X_train, y_train)
pred = classifier.predict(X_test)
score = metrics.accuracy_score(y_test, pred)
print("accuracy:   %0.3f" % score)
cm = metrics.confusion_matrix(y_test, pred)

accuracy:   0.916


In [49]:
score

0.9164871582435791

In [50]:
cm

array([[3201,  188],
       [ 316, 2330]])

In [53]:
# applying PassiveAggressiveClassifier
from sklearn.linear_model import PassiveAggressiveClassifier
linear_clf = PassiveAggressiveClassifier(max_iter=50)
linear_clf.fit(X_train, y_train)
pred1 = linear_clf.predict(X_test)
score1 = metrics.accuracy_score(y_test, pred1)
print("accuracy:   %0.3f" % score1)
cm1 = metrics.confusion_matrix(y_test, pred1)

accuracy:   0.960


In [54]:
cm1

array([[3264,  125],
       [ 117, 2529]])

In [63]:
# Using Logistic Regresstion 
from sklearn.linear_model import LogisticRegression
logistic = LogisticRegression(max_iter=500)
logistic.fit(X_train, y_train)
pred2 = logistic.predict(X_test)
score2 = metrics.accuracy_score(y_test, pred2)
print("accuracy:   %0.3f" % score2)
cm2 = metrics.confusion_matrix(y_test, pred2)

accuracy:   0.963


In [64]:
cm2

array([[3277,  112],
       [ 113, 2533]])

In [73]:
from sklearn.ensemble import RandomForestClassifier
randomclassifier=RandomForestClassifier(n_estimators=200,criterion='entropy')
randomclassifier.fit(X_train, y_train)
pred3 = randomclassifier.predict(X_test)
score3 = metrics.accuracy_score(y_test, pred3)
print("accuracy:   %0.3f" % score3)
cm3 = metrics.confusion_matrix(y_test, pred3)

accuracy:   0.967


In [69]:
cm3

array([[3308,   81],
       [ 106, 2540]])

In [74]:
score3

0.9671913835956918